#!/bin/bash

# Loop through each directory in the current folder
for dir in */; do
    if [ -d "$dir" ]; then
        cd "./$dir"

        # Check if lmp2.sh exists before submitting
        if [ -f "lmp2.sh" ]; then
            # Submit the lmp2.sh script
            sbatch lmp2.sh
        else
            echo "lmp2.sh not found in $dir"
        fi

        # Go back to the parent directory
        cd ../

        # Wait for 2 seconds
        sleep 2
    fi
done
